# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@9db7f66e8e16b5699a514448ce994936c63f0d54
        with:
          deno-version: 1.30.2

      - name: Run type checking on production code
        run: deno check main.ts

      - name: Verify formatting
        run: deno fmt --check **/*.ts

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
